### ISSUE TITLE
Signup with Social network Facebook/Twitter/Google

### ISSUE THREAD

**Issue by Foorack** [TheBanHammer/NightcoreIssues#25]
Add functionality to register and login with a/multiple social account(s).

Thanks to @oDeathwingo for the idea. I deleted the comment you made and recreated it as a separate issue.

**Comment by minymind** [comment]
dont know if it is alredy finished but i tryd to logon with Google and got this.
i hope this might helped ;3

Cannot GET /o/oauth2?access_type=online&amp;scope=email&amp;response_type=code&amp;client_id=888820713522-7d9ci8onfjqlqg4qn0srgpns9unptt23.apps.googleusercontent.com&amp;redirect_uri=http%3A%2F%2Falpha.nightcore-331.net%2Foauthgoogle

**Comment by enteryournamehere** [comment]
Known bug, will probably be fixed in the next update
