### ISSUE TITLE
Song wouldn't advance

### ISSUE THREAD

**Issue by Zombosaur** [TheBanHammer/NightcoreIssues#27]
Song ended and it didn't change to the next song, had to skip

**Comment by Foorack** [comment]
Thanks for reporting. Added it to our to do list of thing to take a look at.

**Comment by TheBloodMerchant** [comment]
i did i just didn't explain it well so you rejected me :biblethump:

**Comment by Foorack** [comment]
@TheBloodMerchant if you are referring to #8 then I'm  sorry. Added this to our bug list. :+1:
