### ISSUE TITLE
Song Fails to Change on Bad Connection

### ISSUE THREAD

**Issue by gyroninja** [TheBanHammer/NightcoreIssues#65]
If my internet is lagging while the song is changing I seem to miss the broadcast which tells me to load the next song. Hitting refresh does not fix the issue as it just refreshes the current song which is already finished. The workaround I have for this problem is either waiting for the next song to start or manually refreshing the page.

**Comment by enteryournamehere** [comment]
What do you mean exactly? It's not really clear to me.
"Hitting refresh does not fix" and "The workaround (...) is (...) refreshing the page"?
"I seem to miss the broadcast which tells me to load the next song" and "The workaround (...) is (...) waiting for the next song"

**Comment by gyroninja** [comment]
So I am running on the assumption that the sight works by sending a packet that informs me of the next song to play based on what I've seen.

If I miss that packet I am no longer in sync with the server. That means if I hit refresh it is just going to reload the old video and not the video on the server since I am desynchronized.

The packet that broadcasts what song is playing is sent at two different places. 1. When previous song ends. 2. When you load up the site.

My client will become synchronized with the server again if one of those conditions happen from either waiting for the current song (server side) to finish and then get the broadcast for the next packet or I can just refresh the page to get the broadcast for the current song.

**Comment by bentenz5** [comment]
I've had this bug once before, was running on an xfinitywifi hotspot with 1-2 bars of signal on my chromebook. When the song ended, the video just showed a play button, but it wasnt a disconnect as the chat just kept going and chatting. Confirmed it wasnt some sort of lag by asking if I still existed, and chat confirmed i'm still there. Hitting the refresh button on the video player didnt work either, had to reload the page to fix it. Doesnt happen often for me, though, so its not a bother.

**Comment by Aekami** [comment]
"When the song ended, the video just showed a play button"
I had the same once, there was however no need for a reload, as it loaded the next song some time after.

**Comment by gyroninja** [comment]
Maybe try reproducing it by.

1. Load up the site.
2. Unplug your ethernet cable / disconnect from wifi
3. Wait for the song to end
4. Plug back in your ethernet cable / reconnect to wifi

When your internet turns back on you will be desynchronized with the server.
